# Generated by SnakeBridge v0.8.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math_verify ~> 0.1

defmodule MathVerify do
  @moduledoc """
  SnakeBridge bindings for `math_verify`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.MathVerify.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.MathVerify.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.MathVerify.predict(data, __runtime__: [timeout: 600_000])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "math_verify"
  def __snakebridge_library__, do: "math_verify"

  @doc """
  Score an answer against the gold expression.

  Parameters:
  - `gold` (term())
  - `answer` (term())

  Returns:
  - `term()`
  """
  @spec grade(term(), term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def grade(gold, answer, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :grade, [gold, answer], opts)
  end

  @doc """
  Parse an expression into normalized form.

  Parameters:
  - `text` (term())

  Returns:
  - `term()`
  """
  @spec parse(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse(text, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :parse, [text], opts)
  end

  @doc """
  Verify that an answer matches the gold expression.

  Parameters:
  - `gold` (term())
  - `answer` (term())

  Returns:
  - `term()`
  """
  @spec verify(term(), term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def verify(gold, answer, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :verify, [gold, answer], opts)
  end

  @doc false
  def __functions__ do
    [
      {:grade, 2, __MODULE__, "Score an answer against the gold expression."},
      {:parse, 1, __MODULE__, "Parse an expression into normalized form."},
      {:verify, 2, __MODULE__, "Verify that an answer matches the gold expression."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
