# Generated by SnakeBridge v0.5.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math_verify ~> 0.1

defmodule MathVerify do
  @moduledoc """
  SnakeBridge bindings for `math_verify`.
  """

  def __snakebridge_python_name__, do: "math_verify"
  def __snakebridge_library__, do: "math_verify"

  @doc """
  Score an answer against the gold expression.
  """
  @spec grade(term(), term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def grade(gold, answer) do
    SnakeBridge.Runtime.call(__MODULE__, :grade, [gold, answer])
  end

  @doc """
  Parse an expression into normalized form.
  """
  @spec parse(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse(text) do
    SnakeBridge.Runtime.call(__MODULE__, :parse, [text])
  end

  @doc """
  Verify that an answer matches the gold expression.
  """
  @spec verify(term(), term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def verify(gold, answer) do
    SnakeBridge.Runtime.call(__MODULE__, :verify, [gold, answer])
  end

  @doc false
  def __functions__ do
    [
      {:grade, 2, __MODULE__, "Score an answer against the gold expression."},
      {:parse, 1, __MODULE__, "Parse an expression into normalized form."},
      {:verify, 2, __MODULE__, "Verify that an answer matches the gold expression."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
