# Generated by SnakeBridge v0.7.6 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10

defmodule PyLatexEnc do
  @moduledoc """
  SnakeBridge bindings for `pylatexenc`.
  """

  def __snakebridge_python_name__, do: "pylatexenc"
  def __snakebridge_library__, do: "pylatexenc"

  defmodule Latexencode do
    def __snakebridge_python_name__, do: "pylatexenc.latexencode"
    def __snakebridge_library__, do: "pylatexenc"

    @doc """
    Convert unicode text to LaTeX.

    Parameters:
    - `text` (term())

    Returns:
    - `term()`
    """
    @spec unicode_to_latex(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
    def unicode_to_latex(text, opts \\ []) do
      SnakeBridge.Runtime.call(__MODULE__, :unicode_to_latex, [text], opts)
    end
  end

  defmodule Latexwalker.LatexWalker do
    def __snakebridge_python_name__, do: "pylatexenc.latexwalker"
    def __snakebridge_python_class__, do: "LatexWalker"
    def __snakebridge_library__, do: "pylatexenc"
    @opaque t :: SnakeBridge.Ref.t()

    @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
    def new(latex, opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [latex], opts)
    end

    @spec get_latex_nodes(SnakeBridge.Ref.t(), keyword()) ::
            {:ok, term()} | {:error, Snakepit.Error.t()}
    def get_latex_nodes(ref, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :get_latex_nodes, [], opts)
    end
  end

  @doc false
  def __functions__ do
    [
      {:unicode_to_latex, 1, __MODULE__, "Convert unicode text to LaTeX."}
    ]
  end

  @doc false
  def __classes__ do
    [
      {PyLatexEnc.Latexwalker.LatexWalker, "Walk a LaTeX string and parse nodes."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
