# Generated by SnakeBridge v0.5.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10

defmodule PyLatexEnc do
  @moduledoc """
  SnakeBridge bindings for `pylatexenc`.
  """

  def __snakebridge_python_name__, do: "pylatexenc"
  def __snakebridge_library__, do: "pylatexenc"

  defmodule Latexencode do
    def __snakebridge_python_name__, do: "pylatexenc.latexencode"

    @doc """
    Convert unicode text to LaTeX.
    """
    @spec unicode_to_latex(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
    def unicode_to_latex(text) do
      SnakeBridge.Runtime.call(__MODULE__, :unicode_to_latex, [text])
    end
  end

  defmodule Latexwalker.LatexWalker do
    def __snakebridge_python_name__, do: "pylatexenc.latexwalker"
    def __snakebridge_python_class__, do: "LatexWalker"

    @spec new(term(), keyword()) :: {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def new(arg, opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [arg], opts)
    end

    @spec get_latex_nodes(Snakepit.PyRef.t()) ::
            {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def get_latex_nodes(ref) do
      SnakeBridge.Runtime.call_method(ref, :get_latex_nodes, [])
    end
  end

  @doc false
  def __functions__ do
    [
      {:unicode_to_latex, 1, __MODULE__, "Convert unicode text to LaTeX."}
    ]
  end

  @doc false
  def __classes__ do
    [
      {PyLatexEnc.Latexwalker.LatexWalker, "Walk a LaTeX string and parse nodes."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
