# Generated by SnakeBridge v0.7.3 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: sympy ~> 1.12

defmodule Sympy do
  @moduledoc """
  SnakeBridge bindings for `sympy`.
  """

  def __snakebridge_python_name__, do: "sympy"
  def __snakebridge_library__, do: "sympy"

  @doc """
  Return a LaTeX representation of an expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec latex(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def latex(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :latex, [expr], opts)
  end

  @doc """
  Simplify a symbolic expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec simplify(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def simplify(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :simplify, [expr], opts)
  end

  @doc """
  Convert text to a SymPy expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec sympify(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sympify(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :sympify, [expr], opts)
  end

  @doc false
  def __functions__ do
    [
      {:latex, 1, __MODULE__, "Return a LaTeX representation of an expression."},
      {:simplify, 1, __MODULE__, "Simplify a symbolic expression."},
      {:sympify, 1, __MODULE__, "Convert text to a SymPy expression."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
