# Generated by SnakeBridge v0.9.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: sympy ~> 1.12

defmodule Sympy do
  @moduledoc """
  SnakeBridge bindings for `sympy`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.Sympy.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.Sympy.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.Sympy.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Elixir.Sympy.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "sympy"
  def __snakebridge_library__, do: "sympy"

  @doc """
  Return a LaTeX representation of an expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec latex(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def latex(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :latex, [expr], opts)
  end

  @doc """
  Simplify a symbolic expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec simplify(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def simplify(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :simplify, [expr], opts)
  end

  @doc """
  Convert text to a SymPy expression.

  Parameters:
  - `expr` (term())

  Returns:
  - `term()`
  """
  @spec sympify(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sympify(expr, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :sympify, [expr], opts)
  end

  @doc false
  def __functions__ do
    [
      {:latex, 1, __MODULE__, "Return a LaTeX representation of an expression."},
      {:simplify, 1, __MODULE__, "Simplify a symbolic expression."},
      {:sympify, 1, __MODULE__, "Convert text to a SymPy expression."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
