# Generated by SnakeBridge v0.7.8 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: wrapper_args_example stdlib

defmodule WrapperArgs do
  @moduledoc """
  SnakeBridge bindings for `wrapper_args_example`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.WrapperArgs.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.WrapperArgs.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.WrapperArgs.predict(data, __runtime__: [timeout: 600_000])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "wrapper_args_example"
  def __snakebridge_library__, do: "wrapper_args_example"

  @doc """
  Join values with a separator, demonstrating Python varargs.

  Parameters:
  - `values` (term())
  - `sep` (term() keyword-only default: ' ')

  Returns:
  - `term()`
  """
  @spec join_values(list(term()), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def join_values(args \\ [], opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call(__MODULE__, :join_values, [] ++ List.wrap(args), opts)
  end

  @doc """
  Compute a simple mean with optional axis and dtype placeholders.

  Parameters:
  - `values` (term())
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `keepdims` (term() default: False)

  Returns:
  - `term()`
  """
  @spec mean(term(), list(term()), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def mean(values, args \\ [], opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call(__MODULE__, :mean, [values] ++ List.wrap(args), opts)
  end

  @doc false
  def __functions__ do
    [
      {:join_values, 0, __MODULE__,
       "Join values with a separator, demonstrating Python varargs."},
      {:mean, 1, __MODULE__, "Compute a simple mean with optional axis and dtype placeholders."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
