# Generated by SnakeBridge v0.7.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: wrapper_args_example stdlib

defmodule WrapperArgs do
  @moduledoc """
  SnakeBridge bindings for `wrapper_args_example`.
  """

  def __snakebridge_python_name__, do: "wrapper_args_example"
  def __snakebridge_library__, do: "wrapper_args_example"

  @doc """
  Join values with a separator, demonstrating Python varargs.
  """
  @spec join_values(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def join_values(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :join_values, [], opts)
  end

  @doc """
  Compute a simple mean with optional axis and dtype placeholders.
  """
  @spec mean(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def mean(values, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :mean, [values], opts)
  end

  @doc false
  def __functions__ do
    [
      {:join_values, 0, __MODULE__,
       "Join values with a separator, demonstrating Python varargs."},
      {:mean, 1, __MODULE__, "Compute a simple mean with optional axis and dtype placeholders."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
