# Generated by SnakeBridge v0.7.8 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib

defmodule ClassConstructor do
  @moduledoc """
  SnakeBridge bindings for `class_constructor_example`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.ClassConstructor.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.ClassConstructor.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.ClassConstructor.predict(data, __runtime__: [timeout: 600_000])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_library__, do: "class_constructor_example"

  defmodule Config do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "Config"
    def __snakebridge_library__, do: "class_constructor_example"
    @opaque t :: SnakeBridge.Ref.t()

    @spec new(term(), list(term()), keyword()) ::
            {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
    def new(path, args \\ [], opts \\ []) do
      {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path] ++ List.wrap(args), opts)
    end

    @spec summary(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
    def summary(ref, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :summary, [], opts)
    end
  end

  defmodule EmptyClass do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "EmptyClass"
    def __snakebridge_library__, do: "class_constructor_example"
    @opaque t :: SnakeBridge.Ref.t()

    @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
    def new(opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
    end
  end

  defmodule Point do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "Point"
    def __snakebridge_library__, do: "class_constructor_example"
    @opaque t :: SnakeBridge.Ref.t()

    @spec new(term(), term(), keyword()) ::
            {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
    def new(x, y, opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [x, y], opts)
    end

    @spec magnitude(SnakeBridge.Ref.t(), keyword()) ::
            {:ok, term()} | {:error, Snakepit.Error.t()}
    def magnitude(ref, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :magnitude, [], opts)
    end
  end

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    [
      {ClassConstructor.Config, "A class with an optional __init__ argument."},
      {ClassConstructor.EmptyClass, "A class with no __init__ arguments."},
      {ClassConstructor.Point, "A class with two required __init__ arguments."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
