# Generated by SnakeBridge v0.7.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib

defmodule ClassConstructor do
  @moduledoc """
  SnakeBridge bindings for `class_constructor_example`.
  """

  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_library__, do: "class_constructor_example"

  defmodule Config do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "Config"

    @spec new(term(), keyword()) :: {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def new(path, opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path], opts)
    end

    @spec summary(Snakepit.PyRef.t(), keyword()) ::
            {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def summary(ref, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :summary, [], opts)
    end
  end

  defmodule EmptyClass do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "EmptyClass"

    @spec new(keyword()) :: {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def new(opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
    end
  end

  defmodule Point do
    def __snakebridge_python_name__, do: "class_constructor_example"
    def __snakebridge_python_class__, do: "Point"

    @spec new(term(), term(), keyword()) ::
            {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def new(x, y, opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [x, y], opts)
    end

    @spec magnitude(Snakepit.PyRef.t(), keyword()) ::
            {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def magnitude(ref, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :magnitude, [], opts)
    end
  end

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    [
      {ClassConstructor.Config, "A class with an optional __init__ argument."},
      {ClassConstructor.EmptyClass, "A class with no __init__ arguments."},
      {ClassConstructor.Point, "A class with two required __init__ arguments."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
