# Generated by SnakeBridge v0.8.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib

defmodule Json do
  @moduledoc """
  SnakeBridge bindings for `json`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.Json.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.Json.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.Json.predict(data, __runtime__: [timeout: 600_000])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "json"
  def __snakebridge_library__, do: "json"

  @doc """
  Serialize obj to a JSON formatted str.

  Parameters:
  - `obj` (term())
  - `skipkeys` (term() keyword-only, required)

  Returns:
  - `term()`
  """
  @spec dumps(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dumps(obj, opts \\ []) do
    kw_keys = opts |> Keyword.keys() |> Enum.map(&to_string/1)
    missing_kw = ["skipkeys"] |> Enum.reject(&(&1 in kw_keys))

    if missing_kw != [] do
      raise ArgumentError,
            "Missing required keyword-only arguments: " <> Enum.join(missing_kw, ", ")
    end

    SnakeBridge.Runtime.call(__MODULE__, :dumps, [obj], opts)
  end

  @doc """
  Deserialize s to a Python object.

  Parameters:
  - `s` (term())

  Returns:
  - `term()`
  """
  @spec loads(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def loads(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :loads, [s], opts)
  end

  defmodule Encoder.JSONEncoder do
    def __snakebridge_python_name__, do: "json.encoder"
    def __snakebridge_python_class__, do: "JSONEncoder"
    def __snakebridge_library__, do: "json"
    @opaque t :: SnakeBridge.Ref.t()

    @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
    def new(opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
    end

    @spec encode(SnakeBridge.Ref.t(), term(), keyword()) ::
            {:ok, term()} | {:error, Snakepit.Error.t()}
    def encode(ref, o, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :encode, [o], opts)
    end

    @spec item_separator(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
    def item_separator(ref) do
      SnakeBridge.Runtime.get_attr(ref, :item_separator)
    end
  end

  @doc false
  def __functions__ do
    [
      {:dumps, 1, __MODULE__, "Serialize obj to a JSON formatted str."},
      {:loads, 1, __MODULE__, "Deserialize s to a Python object."}
    ]
  end

  @doc false
  def __classes__ do
    [
      {Json.Encoder.JSONEncoder, "Extensible JSON encoder for Python data structures."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
