# Generated by SnakeBridge v0.7.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib

defmodule Json do
  @moduledoc """
  SnakeBridge bindings for `json`.
  """

  def __snakebridge_python_name__, do: "json"
  def __snakebridge_library__, do: "json"

  @doc """
  Serialize obj to a JSON formatted str.
  """
  @spec dumps(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dumps(obj, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :dumps, [obj], opts)
  end

  @doc """
  Deserialize s to a Python object.
  """
  @spec loads(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def loads(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :loads, [s], opts)
  end

  defmodule Encoder.JSONEncoder do
    def __snakebridge_python_name__, do: "json.encoder"
    def __snakebridge_python_class__, do: "JSONEncoder"

    @spec new(keyword()) :: {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def new(opts \\ []) do
      SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
    end

    @spec encode(Snakepit.PyRef.t(), term(), keyword()) ::
            {:ok, Snakepit.PyRef.t()} | {:error, Snakepit.Error.t()}
    def encode(ref, o, opts \\ []) do
      SnakeBridge.Runtime.call_method(ref, :encode, [o], opts)
    end

    @spec item_separator(Snakepit.PyRef.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
    def item_separator(ref) do
      SnakeBridge.Runtime.get_attr(ref, :item_separator)
    end
  end

  @doc false
  def __functions__ do
    [
      {:dumps, 1, __MODULE__, "Serialize obj to a JSON formatted str."},
      {:loads, 1, __MODULE__, "Deserialize s to a Python object."}
    ]
  end

  @doc false
  def __classes__ do
    [
      {Json.Encoder.JSONEncoder, "Extensible JSON encoder for Python data structures."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
