# Generated by SnakeBridge v0.7.3 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math stdlib

defmodule Math do
  @moduledoc """
  SnakeBridge bindings for `math`.
  """

  def __snakebridge_python_name__, do: "math"
  def __snakebridge_library__, do: "math"

  @doc """
  Return the cosine of x.

  Parameters:
  - `x` (term())

  Returns:
  - `term()`
  """
  @spec cos(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cos(x, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :cos, [x], opts)
  end

  @doc """
  Return the sine of x.

  Parameters:
  - `x` (term())

  Returns:
  - `term()`
  """
  @spec sin(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sin(x, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :sin, [x], opts)
  end

  @doc """
  Return the square root of x.

  Parameters:
  - `x` (term())

  Returns:
  - `term()`
  """
  @spec sqrt(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sqrt(x, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :sqrt, [x], opts)
  end

  @doc false
  def __functions__ do
    [
      {:cos, 1, __MODULE__, "Return the cosine of x."},
      {:sin, 1, __MODULE__, "Return the sine of x."},
      {:sqrt, 1, __MODULE__, "Return the square root of x."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
