# Generated by SnakeBridge v3.0.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math stdlib

defmodule Math do
  @moduledoc """
  SnakeBridge bindings for `math`.
  """

  def __snakebridge_python_name__, do: "math"
  def __snakebridge_library__, do: "math"

  @doc """
  Return the cosine of x.
  """
  @spec cos(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cos(x) do
    SnakeBridge.Runtime.call(__MODULE__, :cos, [x])
  end

  @doc """
  Return the sine of x.
  """
  @spec sin(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sin(x) do
    SnakeBridge.Runtime.call(__MODULE__, :sin, [x])
  end

  @doc """
  Return the square root of x.
  """
  @spec sqrt(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sqrt(x) do
    SnakeBridge.Runtime.call(__MODULE__, :sqrt, [x])
  end

  @doc false
  def __functions__ do
    [
      {:cos, 1, __MODULE__, "Return the cosine of x."},
      {:sin, 1, __MODULE__, "Return the sine of x."},
      {:sqrt, 1, __MODULE__, "Return the square root of x."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
