# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.tool

defmodule Json.Tool do
  @moduledoc """
  Submodule bindings for `json.tool`.
  """

  def __snakebridge_python_name__, do: "json.tool"
  def __snakebridge_library__, do: "json"

  @doc """
  Command-line tool to validate and pretty-print JSON

  Usage::

    $ echo '{"json":"obj"}' | python -m json.tool
    {
        "json": "obj"
    }
    $ echo '{ 1.2:3.4}' | python -m json.tool
    Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

  Returns:
  - `term()`
  """
  @spec main(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def main(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :main, [], opts)
  end
end
