# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: numpy stdlib
# Python module: numpy
# Python class: ndarray

defmodule Numpy.Ndarray do
  @moduledoc """
  ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

  An array object represents a multidimensional, homogeneous array
  of fixed-size items.  An associated data-type object describes the
  format of each element in the array (its byte-order, how many bytes it
  occupies in memory, whether it is an integer, a floating point number,
  or something else, etc.)

  Arrays should be constructed using `array`, `zeros` or `empty` (refer
  to the See Also section below).  The parameters given here refer to
  a low-level method (`ndarray(...)`) for instantiating an array.

  For more information, refer to the `numpy` module and examine the
  methods and attributes of an array.

  ## Parameters

  - `(for the __new__ method; see Notes below)` - 
  - `shape` - tuple of ints Shape of created array.
  - `dtype` - data-type, optional Any object that can be interpreted as a numpy data type. Default is `numpy.float64`.
  - `buffer` - object exposing buffer interface, optional Used to fill the array with data.
  - `offset` - int, optional Offset of array data in buffer.
  - `strides` - tuple of ints, optional Strides of data in memory.
  - `order` - {'C', 'F'}, optional Row-major (C-style) or column-major (Fortran-style) order.

  ## Examples

      These examples illustrate the low-level `ndarray` constructor.  Refer
      to the `See Also` section above for easier ways of constructing an
      ndarray.

      First mode, `buffer` is None:

      iex> import numpy as np
      iex> np.ndarray(shape=(2,2), dtype=float, order='F')
      array([[0.0e+000, 0.0e+000], # random
      [     nan, 2.5e-323]])

      Second mode:

      iex> np.ndarray((2,), buffer=np.array([1,2,3]),
      ...> offset=np.int_().itemsize,
      ...> dtype=int) # offset = 1*itemsize, i.e. skip first element
      array([2, 3])

  ## Notes

  There are two modes of creating an array using ``__new__``:

  1. If `buffer` is None, then only `shape`, `dtype`, and `order`
     are used.
  2. If `buffer` is an object exposing the buffer interface, then
     all keywords are interpreted.

  No ``__init__`` method is needed because the array is fully initialized
  after the ``__new__`` method.
  """
  def __snakebridge_python_name__, do: "numpy"
  def __snakebridge_python_class__, do: "ndarray"
  def __snakebridge_library__, do: "numpy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  Parameters:
  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.byteswap(inplace=False)

  Swap the bytes of the array elements

  Toggle between low-endian and big-endian data representation by
  returning a byteswapped array, optionally swapped in-place.
  Arrays of byte-strings are not swapped. The real and imaginary
  parts of a complex number are swapped individually.

  ## Parameters

  - `inplace` - bool, optional If ``True``, swap bytes in-place, default is ``False``.

  ## Returns

  Returns `out`. ndarray The byteswapped array. If `inplace` is ``True``, this is a view to self.

  ## Examples

      iex> import numpy as np
      iex> A = np.array([1, 256, 8755], dtype=np.int16)
      iex> list(map(hex, A))
      ['0x1', '0x100', '0x2233']
      iex> A.byteswap(inplace=True)
      array([  256,     1, 13090], dtype=int16)
      iex> list(map(hex, A))
      ['0x100', '0x1', '0x3322']

      Arrays of byte-strings are not swapped

      iex> A = np.array([b'ceg', b'fac'])
      iex> A.byteswap()
      array([b'ceg', b'fac'], dtype='|S3')

      ``A.view(A.dtype.newbyteorder()).byteswap()`` produces an array with
      the same values but different representation in memory

      iex> A = np.array([1, 2, 3],dtype=np.int64)
      iex> A.view(np.uint8)
      array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
      0, 0], dtype=uint8)
      iex> A.view(A.dtype.newbyteorder()).byteswap(inplace=True)
      array([1, 2, 3], dtype='>i8')
      iex> A.view(np.uint8)
      array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
      0, 3], dtype=uint8)

  Parameters:
  - `inplace` (term() default: False)

  Returns:
  - `term()`
  """
  @spec byteswap(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def byteswap(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :byteswap, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.diagonal(offset=0, axis1=0, axis2=1)

  Return specified diagonals. In NumPy 1.9 the returned array is a
  read-only view instead of a copy as in previous NumPy versions.  In
  a future version the read-only restriction will be removed.

  Refer to :func:`numpy.diagonal` for full documentation.

  Parameters:
  - `offset` (term() default: 0)
  - `axis1` (term() default: 0)
  - `axis2` (term() default: 1)

  Returns:
  - `term()`
  """
  @spec diagonal(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def diagonal(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :diagonal, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

  Copy of the array, cast to a specified type.

  ## Parameters

  - `dtype` - str or dtype Typecode or data-type to which the array is cast.
  - `order` - {'C', 'F', 'A', 'K'}, optional Controls the memory layout order of the result. 'C' means C order, 'F' means Fortran order, 'A' means 'F' order if all the arrays are Fortran contiguous, 'C' order otherwise, and 'K' means as close to the order the array elements appear in memory as possible. Default is 'K'.
  - `casting` - {'no', 'equiv', 'safe', 'same_kind', 'same_value', 'unsafe'}, optional Controls what kind of data casting may occur. Defaults to 'unsafe' for backwards compatibility.
  - `subok` - bool, optional If True, then sub-classes will be passed-through (default), otherwise the returned array will be forced to be a base-class array.
  - `copy` - bool, optional By default, astype always returns a newly allocated array. If this is set to false, and the `dtype`, `order`, and `subok` requirements are satisfied, the input array is returned instead of a copy.

  ## Returns

  Returns `arr_t`. ndarray Unless `copy` is False and the other conditions for returning the input array are satisfied (see description for `copy` input parameter), `arr_t` is a new array of the same shape as the input array, with dtype, order given by `dtype`, `order`.

  ## Raises

  - `ComplexWarning When casting from complex to float or int. To avoid this, one should use ``a.real.astype(t)``.` - 
  - `ValueError When casting using ``'same_value'`` and the values change or would overflow` - 

  ## Examples

      iex> import numpy as np
      iex> x = np.array([1, 2, 2.5])
      iex> x
      array([1. ,  2. ,  2.5])

      iex> x.astype(int)
      array([1, 2, 2])

      iex> x.astype(int, casting="same_value")
      Traceback (most recent call last):
      ...> 
      ValueError: could not cast 'same_value' double to long

      iex> x[:2].astype(int, casting="same_value")
      array([1, 2])

  Parameters:
  - `dtype` (term())
  - `order` (term() default: 'K')
  - `casting` (term() default: 'unsafe')
  - `subok` (term() default: True)
  - `copy` (term() default: True)

  Returns:
  - `term()`
  """
  @spec astype(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def astype(ref, dtype, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :astype, [dtype] ++ List.wrap(args), opts)
  end

  @doc """
  a.reshape(shape, /, *, order='C', copy=None)

  a.reshape(*shape, order='C', copy=None)

  Returns an array containing the same data with a new shape.

  Refer to `numpy.reshape` for full documentation.

  Parameters:
  - `shape` (term())
  - `order` (term() keyword-only default: 'C')
  - `copy` (term() keyword-only default: None)

  Returns:
  - `term()`
  """
  @spec reshape(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def reshape(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :reshape, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.prod(axis=None, dtype=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

  Return the product of the array elements over the given axis

  Refer to `numpy.prod` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec prod(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def prod(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :prod, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.squeeze(axis=None)

  Remove axes of length one from `a`.

  Refer to `numpy.squeeze` for full documentation.

  Parameters:
  - `axis` (term() default: None)

  Returns:
  - `term()`
  """
  @spec squeeze(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def squeeze(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :squeeze, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.max(axis=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

  Return the maximum along a given axis.

  Refer to `numpy.amax` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec max(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def max(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :max, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.tofile(fid, /, sep='', format='%s')

  Write array to a file as text or binary (default).

  Data is always written in 'C' order, independent of the order of `a`.
  The data produced by this method can be recovered using the function
  fromfile().

  ## Parameters

  - `fid` - file or str or Path An open file object, or a string containing a filename.
  - `sep` - str Separator between array items for text output. If "" (empty), a binary file is written, equivalent to ``file.write(a.tobytes())``.
  - `format` - str Format string for text file output. Each entry in the array is formatted to text by first converting it to the closest Python type, and then using "format" % item.

  ## Notes

  This is a convenience function for quick storage of array data.
  Information on endianness and precision is lost, so this method is not a
  good choice for files intended to archive data or transport data between
  machines with different endianness. Some of these problems can be overcome
  by outputting the data as text files, at the expense of speed and file
  size.

  When fid is a file object, array contents are directly written to the
  file, bypassing the file object's ``write`` method. As a result, tofile
  cannot be used with files objects supporting compression (e.g., GzipFile)
  or file-like objects that do not support ``fileno()`` (e.g., BytesIO).

  Parameters:
  - `fid` (term())
  - `sep` (term() default: '')
  - `format` (term() default: '%s')

  Returns:
  - `term()`
  """
  @spec tofile(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def tofile(ref, fid, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :tofile, [fid] ++ List.wrap(args), opts)
  end

  @doc """
  a.compress(condition, axis=None, out=None)

  Return selected slices of this array along given axis.

  Refer to `numpy.compress` for full documentation.

  Parameters:
  - `condition` (term())
  - `axis` (term() default: None)
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec compress(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def compress(ref, condition, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :compress, [condition] ++ List.wrap(args), opts)
  end

  @doc """
  a.copy(order='C')

  Return a copy of the array.

  ## Parameters

  - `order` - {'C', 'F', 'A', 'K'}, optional Controls the memory layout of the copy. 'C' means C-order, 'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous, 'C' otherwise. 'K' means match the layout of `a` as closely as possible. (Note that this function and :func:`numpy.copy` are very similar but have different default values for their order= arguments, and this function always passes sub-classes through.)

  ## Examples

      iex> import numpy as np
      iex> x = np.array([[1,2,3],[4,5,6]], order='F')

      iex> y = x.copy()

      iex> x.fill(0)

      iex> x
      array([[0, 0, 0],
      [0, 0, 0]])

      iex> y
      array([[1, 2, 3],
      [4, 5, 6]])

      iex> y.flags['C_CONTIGUOUS']
      True

      For arrays containing Python objects (e.g. dtype=object),
      the copy is a shallow one. The new array will contain the
      same object which may lead to surprises if that object can
      be modified (is mutable):

      iex> a = np.array([1, 'm', [2, 3, 4]], dtype=object)
      iex> b = a.copy()
      iex> b[2][0] = 10
      iex> a
      array([1, 'm', list([10, 3, 4])], dtype=object)

      To ensure all elements within an ``object`` array are copied,
      use `copy.deepcopy`:

      iex> import copy
      iex> a = np.array([1, 'm', [2, 3, 4]], dtype=object)
      iex> c = copy.deepcopy(a)
      iex> c[2][0] = 10
      iex> c
      array([1, 'm', list([10, 3, 4])], dtype=object)
      iex> a
      array([1, 'm', list([2, 3, 4])], dtype=object)

  ## Notes

  This function is the preferred method for creating an array copy.  The
  function :func:`numpy.copy` is similar, but it defaults to using order 'K',
  and will not pass sub-classes through by default.

  Parameters:
  - `order` (term() default: 'C')

  Returns:
  - `term()`
  """
  @spec copy(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def copy(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :copy, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.argmin(axis=None, out=None, *, keepdims=False)

  Return indices of the minimum values along the given axis.

  Refer to `numpy.argmin` for detailed documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `keepdims` (term() keyword-only default: False)

  Returns:
  - `term()`
  """
  @spec argmin(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def argmin(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :argmin, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.getfield(dtype, offset=0)

  Returns a field of the given array as a certain type.

  A field is a view of the array data with a given data-type. The values in
  the view are determined by the given type and the offset into the current
  array in bytes. The offset needs to be such that the view dtype fits in the
  array dtype; for example an array of dtype complex128 has 16-byte elements.
  If taking a view with a 32-bit integer (4 bytes), the offset needs to be
  between 0 and 12 bytes.

  ## Parameters

  - `dtype` - str or dtype The data type of the view. The dtype size of the view can not be larger than that of the array itself.
  - `offset` - int Number of bytes to skip before beginning the element view.

  ## Examples

      iex> import numpy as np
      iex> x = np.diag([1.+1.j]*2)
      iex> x[1, 1] = 2 + 4.j
      iex> x
      array([[1.+1.j,  0.+0.j],
      [0.+0.j,  2.+4.j]])
      iex> x.getfield(np.float64)
      array([[1.,  0.],
      [0.,  2.]])

      By choosing an offset of 8 bytes we can select the complex part of the
      array for our view:

      iex> x.getfield(np.float64, offset=8)
      array([[1.,  0.],
      [0.,  4.]])

  Parameters:
  - `dtype` (term())
  - `offset` (term() default: 0)

  Returns:
  - `term()`
  """
  @spec getfield(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def getfield(ref, dtype, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :getfield, [dtype] ++ List.wrap(args), opts)
  end

  @doc """
  a.fill(value)

  Fill the array with a scalar value.

  ## Parameters

  - `value` - scalar All elements of `a` will be assigned this value.

  ## Examples

      iex> import numpy as np
      iex> a = np.array([1, 2])
      iex> a.fill(0)
      iex> a
      array([0, 0])
      iex> a = np.empty(2)
      iex> a.fill(1)
      iex> a
      array([1.,  1.])

      Fill expects a scalar value and always behaves the same as assigning
      to a single array element.  The following is a rare example where this
      distinction is important:

      iex> a = np.array([None, None], dtype=object)
      iex> a[0] = np.array(3)
      iex> a
      array([array(3), None], dtype=object)
      iex> a.fill(np.array(3))
      iex> a
      array([array(3), array(3)], dtype=object)

      Where other forms of assignments will unpack the array being assigned:

      iex> a[...] = np.array(3)
      iex> a
      array([3, 3], dtype=object)

  Parameters:
  - `value` (term())

  Returns:
  - `term()`
  """
  @spec fill(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def fill(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :fill, [value], opts)
  end

  @doc """
  a.choose(choices, out=None, mode='raise')

  Use an index array to construct a new array from a set of choices.

  Refer to `numpy.choose` for full documentation.

  Parameters:
  - `choices` (term())
  - `out` (term() default: None)
  - `mode` (term() default: 'raise')

  Returns:
  - `term()`
  """
  @spec choose(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def choose(ref, choices, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :choose, [choices] ++ List.wrap(args), opts)
  end

  @doc """
  a.cumprod(axis=None, dtype=None, out=None)

  Return the cumulative product of the elements along the given axis.

  Refer to `numpy.cumprod` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec cumprod(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cumprod(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :cumprod, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.setflags(write=None, align=None, uic=None)

  Set array flags WRITEABLE, ALIGNED, WRITEBACKIFCOPY,
  respectively.

  These Boolean-valued flags affect how numpy interprets the memory
  area used by `a` (see Notes below). The ALIGNED flag can only
  be set to True if the data is actually aligned according to the type.
  The WRITEBACKIFCOPY flag can never be set
  to True. The flag WRITEABLE can only be set to True if the array owns its
  own memory, or the ultimate owner of the memory exposes a writeable buffer
  interface, or is a string. (The exception for string is made so that
  unpickling can be done without copying memory.)

  ## Parameters

  - `write` - bool, optional Describes whether or not `a` can be written to.
  - `align` - bool, optional Describes whether or not `a` is aligned properly for its type.
  - `uic` - bool, optional Describes whether or not `a` is a copy of another "base" array.

  ## Examples

      iex> import numpy as np
      iex> y = np.array([[3, 1, 7],
      ...> [2, 0, 0],
      ...> [8, 5, 9]])
      iex> y
      array([[3, 1, 7],
      [2, 0, 0],
      [8, 5, 9]])
      iex> y.flags
      C_CONTIGUOUS : True
      F_CONTIGUOUS : False
      OWNDATA : True
      WRITEABLE : True
      ALIGNED : True
      WRITEBACKIFCOPY : False
      iex> y.setflags(write=0, align=0)
      iex> y.flags
      C_CONTIGUOUS : True
      F_CONTIGUOUS : False
      OWNDATA : True
      WRITEABLE : False
      ALIGNED : False
      WRITEBACKIFCOPY : False
      iex> y.setflags(uic=1)
      Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      ValueError: cannot set WRITEBACKIFCOPY flag to True

  ## Notes

  Array flags provide information about how the memory area used
  for the array is to be interpreted. There are 7 Boolean flags
  in use, only three of which can be changed by the user:
  WRITEBACKIFCOPY, WRITEABLE, and ALIGNED.

  WRITEABLE (W) the data area can be written to;

  ALIGNED (A) the data and strides are aligned appropriately for the hardware
  (as determined by the compiler);

  WRITEBACKIFCOPY (X) this array is a copy of some other array (referenced
  by .base). When the C-API function PyArray_ResolveWritebackIfCopy is
  called, the base array will be updated with the contents of this array.

  All flags can be accessed using the single (upper case) letter as well
  as the full name.

  Parameters:
  - `write` (term() keyword-only default: None)
  - `align` (term() keyword-only default: None)
  - `uic` (term() keyword-only default: None)

  Returns:
  - `term()`
  """
  @spec setflags(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def setflags(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :setflags, [], opts)
  end

  @doc """
  a.all(axis=None, out=None, *, keepdims=<no value>, where=<no value>)

  Returns True if all elements evaluate to True.

  Refer to `numpy.all` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `keepdims` (term() default: False)
  - `where` (term() keyword-only default: True)

  Returns:
  - `term()`
  """
  @spec all(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def all(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :all, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.any(axis=None, out=None, *, keepdims=<no value>, where=<no value>)

  Returns True if any of the elements of `a` evaluate to True.

  Refer to `numpy.any` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `keepdims` (term() default: False)
  - `where` (term() keyword-only default: True)

  Returns:
  - `term()`
  """
  @spec any(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def any(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :any, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.put(indices, values, mode='raise')

  Set ``a.flat[n] = values[n]`` for all ``n`` in indices.

  Refer to `numpy.put` for full documentation.

  Parameters:
  - `indices` (term())
  - `values` (term())
  - `mode` (term() default: 'raise')

  Returns:
  - `term()`
  """
  @spec put(SnakeBridge.Ref.t(), term(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def put(ref, indices, values, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :put, [indices, values] ++ List.wrap(args), opts)
  end

  @doc """
  a.item(*args)

  Copy an element of an array to a standard Python scalar and return it.

  ## Parameters

  - `\*args` - Arguments (variable number and type)

  ## Returns

  Returns `z`. Standard Python scalar object A copy of the specified element of the array as a suitable Python scalar

  ## Examples

      iex> import numpy as np
      iex> np.random.seed(123)
      iex> x = np.random.randint(9, size=(3, 3))
      iex> x
      array([[2, 2, 6],
      [1, 3, 6],
      [1, 0, 1]])
      iex> x.item(3)
      1
      iex> x.item(7)
      0
      iex> x.item((0, 1))
      2
      iex> x.item((2, 2))
      1

      For an array with object dtype, elements are returned as-is.

      iex> a = np.array([np.int64(1)], dtype=object)
      iex> a.item() #return np.int64
      np.int64(1)

  ## Notes

  When the data type of `a` is longdouble or clongdouble, item() returns
  a scalar array object because there is no available Python scalar that
  would not lose information. Void arrays return a buffer object for item(),
  unless fields are defined, in which case a tuple is returned.

  `item` is very similar to a[args], except, instead of an array scalar,
  a standard Python scalar is returned. This can be useful for speeding up
  access to elements of the array and doing arithmetic on elements of the
  array using Python's optimized math.

  Parameters:
  - `args` (term())

  Returns:
  - `term()`
  """
  @spec item(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def item(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :item, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.view([dtype][, type])

  New view of array with the same data.

  .. note::
      Passing None for ``dtype`` is different from omitting the parameter,
      since the former invokes ``dtype(None)`` which is an alias for
      ``dtype('float64')``.

  ## Parameters

  - `dtype` - data-type or ndarray sub-class, optional Data-type descriptor of the returned view, e.g., float32 or int16. Omitting it results in the view having the same data-type as `a`. This argument can also be specified as an ndarray sub-class, which then specifies the type of the returned object (this is equivalent to setting the ``type`` parameter).
  - `type` - Python type, optional Type of the returned view, e.g., ndarray or matrix.  Again, omission of the parameter results in type preservation.

  ## Examples

      iex> import numpy as np
      iex> x = np.array([(-1, 2)], dtype=[('a', np.int8), ('b', np.int8)])

      Viewing array data using a different type and dtype:

      iex> nonneg = np.dtype([("a", np.uint8), ("b", np.uint8)])
      iex> y = x.view(dtype=nonneg, type=np.recarray)
      iex> x["a"]
      array([-1], dtype=int8)
      iex> y.a
      array([255], dtype=uint8)

      Creating a view on a structured array so it can be used in calculations

      iex> x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
      iex> xv = x.view(dtype=np.int8).reshape(-1,2)
      iex> xv
      array([[1, 2],
      [3, 4]], dtype=int8)
      iex> xv.mean(0)
      array([2.,  3.])

      Making changes to the view changes the underlying array

      iex> xv[0,1] = 20
      iex> x
      array([(1, 20), (3,  4)], dtype=[('a', 'i1'), ('b', 'i1')])

      Using a view to convert an array to a recarray:

      iex> z = x.view(np.recarray)
      iex> z.a
      array([1, 3], dtype=int8)

      Views share data:

      iex> x[0] = (9, 10)
      iex> z[0]
      np.record((9, 10), dtype=[('a', 'i1'), ('b', 'i1')])

      Views that change the dtype size (bytes per entry) should normally be
      avoided on arrays defined by slices, transposes, fortran-ordering, etc.:

      iex> x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
      iex> y = x[:, ::2]
      iex> y
      array([[1, 3],
      [4, 6]], dtype=int16)
      iex> y.view(dtype=[('width', np.int16), ('length', np.int16)])
      Traceback (most recent call last):
      ...> 
      ValueError: To change to a dtype of a different size, the last axis must be contiguous
      iex> z = y.copy()
      iex> z.view(dtype=[('width', np.int16), ('length', np.int16)])
      array([[(1, 3)],
      [(4, 6)]], dtype=[('width', '<i2'), ('length', '<i2')])

      However, views that change dtype are totally fine for arrays with a
      contiguous last axis, even if the rest of the axes are not C-contiguous:

      iex> x = np.arange(2 * 3 * 4, dtype=np.int8).reshape(2, 3, 4)
      iex> x.transpose(1, 0, 2).view(np.int16)
      array([[[ 256,  770],
      [3340, 3854]],
      <BLANKLINE>
      [[1284, 1798],
      [4368, 4882]],
      <BLANKLINE>
      [[2312, 2826],
      [5396, 5910]]], dtype=int16)

  ## Notes

  ``a.view()`` is used two different ways:

  ``a.view(some_dtype)`` or ``a.view(dtype=some_dtype)`` constructs a view
  of the array's memory with a different data-type.  This can cause a
  reinterpretation of the bytes of memory.

  ``a.view(ndarray_subclass)`` or ``a.view(type=ndarray_subclass)`` just
  returns an instance of `ndarray_subclass` that looks at the same array
  (same shape, dtype, etc.)  This does not cause a reinterpretation of the
  memory.

  For ``a.view(some_dtype)``, if ``some_dtype`` has a different number of
  bytes per entry than the previous dtype (for example, converting a regular
  array to a structured array), then the last axis of ``a`` must be
  contiguous. This axis will be resized in the result.

  .. versionchanged:: 1.23.0
     Only the last axis needs to be contiguous. Previously, the entire array
     had to be C-contiguous.

  Parameters:
  - `args` (term())
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec view(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def view(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :view, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.resize(new_shape, /, *, refcheck=True)

  a.resize(*new_shape, refcheck=True)

  Change shape and size of array in-place.

  ## Parameters

  - `new_shape` - tuple of ints, or `n` ints Shape of resized array.
  - `refcheck` - bool, optional If False, reference count will not be checked. Default is True.

  ## Returns

  Returns `nil`. 

  ## Raises

  - `ValueError If `a` does not own its own data or references or views to it exist, and the data memory must be changed. PyPy only: will always raise if the data memory must be changed, since there is no reliable way to determine if references or views to it exist.` - 
  - `SystemError If the `order` keyword argument is specified. This behaviour is a bug in NumPy.` - 

  ## Examples

      Shrinking an array: array is flattened (in the order that the data are
      stored in memory), resized, and reshaped:

      iex> import numpy as np

      iex> a = np.array([[0, 1], [2, 3]], order='C')
      iex> a.resize((2, 1))
      iex> a
      array([[0],
      [1]])

      iex> a = np.array([[0, 1], [2, 3]], order='F')
      iex> a.resize((2, 1))
      iex> a
      array([[0],
      [2]])

      Enlarging an array: as above, but missing entries are filled with zeros:

      iex> b = np.array([[0, 1], [2, 3]])
      iex> b.resize(2, 3) # new_shape parameter doesn't have to be a tuple
      iex> b
      array([[0, 1, 2],
      [3, 0, 0]])

      Referencing an array prevents resizing...

      iex> c = a
      iex> a.resize((1, 1))
      Traceback (most recent call last):
      ...> 
      ValueError: cannot resize an array that references or is referenced ...

      Unless `refcheck` is False:

      iex> a.resize((1, 1), refcheck=False)
      iex> a
      array([[0]])
      iex> c
      array([[0]])

  ## Notes

  This reallocates space for the data area if necessary.

  Only contiguous arrays (data elements consecutive in memory) can be
  resized.

  The purpose of the reference count check is to make sure you
  do not use this array as a buffer for another Python object and then
  reallocate the memory. However, reference counts can increase in
  other ways so if you are sure that you have not shared the memory
  for this array with another Python object, then you may safely set
  `refcheck` to False.

  Parameters:
  - `new_shape` (term())
  - `refcheck` (term() keyword-only default: True)

  Returns:
  - `term()`
  """
  @spec resize(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def resize(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :resize, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.to_device(device, /, *, stream=None)

  For Array API compatibility.  Since NumPy only supports CPU arrays, this
  method is a no-op that returns the same array.

  ## Parameters

  - `device` - "cpu" Must be ``"cpu"``.
  - `stream` - None, optional Currently unsupported.

  ## Returns

  Returns `out`. Self Returns the same array.

  Parameters:
  - `device` (term())
  - `stream` (term() keyword-only default: None)

  Returns:
  - `term()`
  """
  @spec to_device(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def to_device(ref, device, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :to_device, [device], opts)
  end

  @doc """
  a.tolist()

  Return the array as an ``a.ndim``-levels deep nested list of Python scalars.

  Return a copy of the array data as a (nested) Python list.
  Data items are converted to the nearest compatible builtin Python type, via
  the `~numpy.ndarray.item` method.

  If ``a.ndim`` is 0, then since the depth of the nested list is 0, it will
  not be a list at all, but a simple Python scalar.

  ## Parameters

  - `none` - 

  ## Returns

  Returns `y`. object, or list of object, or list of list of object, or ... The possibly nested list of array elements.

  ## Examples

      For a 1D array, ``a.tolist()`` is almost the same as ``list(a)``,
      except that ``tolist`` changes numpy scalars to Python scalars:

      iex> import numpy as np
      iex> a = np.uint32([1, 2])
      iex> a_list = list(a)
      iex> a_list
      [np.uint32(1), np.uint32(2)]
      iex> type(a_list[0])
      <class 'numpy.uint32'>
      iex> a_tolist = a.tolist()
      iex> a_tolist
      [1, 2]
      iex> type(a_tolist[0])
      <class 'int'>

      Additionally, for a 2D array, ``tolist`` applies recursively:

      iex> a = np.array([[1, 2], [3, 4]])
      iex> list(a)
      [array([1, 2]), array([3, 4])]
      iex> a.tolist()
      [[1, 2], [3, 4]]

      The base case for this recursion is a 0D array:

      iex> a = np.array(1)
      iex> list(a)
      Traceback (most recent call last):
      ...> 
      TypeError: iteration over a 0-d array
      iex> a.tolist()
      1

  ## Notes

  The array may be recreated via ``a = np.array(a.tolist())``, although this
  may sometimes lose precision.

  Returns:
  - `term()`
  """
  @spec tolist(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tolist(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :tolist, [], opts)
  end

  @doc """
  a.sum(axis=None, dtype=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

  Return the sum of the array elements over the given axis.

  Refer to `numpy.sum` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec sum(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def sum(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :sum, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.sort(axis=-1, kind=None, order=None, *, stable=None)

  Sort an array in-place. Refer to `numpy.sort` for full documentation.

  ## Parameters

  - `axis` - int, optional Axis along which to sort. Default is -1, which means sort along the last axis.
  - `kind` - {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional Sorting algorithm. The default is 'quicksort'. Note that both 'stable' and 'mergesort' use timsort under the covers and, in general, the actual implementation will vary with datatype. The 'mergesort' option is retained for backwards compatibility.
  - `order` - str or list of str, optional When `a` is an array with fields defined, this argument specifies which fields to compare first, second, etc.  A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.
  - `stable` - bool, optional Sort stability. If ``True``, the returned array will maintain the relative order of ``a`` values which compare as equal. If ``False`` or ``None``, this is not guaranteed. Internally, this option selects ``kind='stable'``. Default: ``None``.

  ## Examples

      iex> import numpy as np
      iex> a = np.array([[1,4], [3,1]])
      iex> a.sort(axis=1)
      iex> a
      array([[1, 4],
      [1, 3]])
      iex> a.sort(axis=0)
      iex> a
      array([[1, 3],
      [1, 4]])

      Use the `order` keyword to specify a field to use when sorting a
      structured array:

      iex> a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
      iex> a.sort(order='y')
      iex> a
      array([(b'c', 1), (b'a', 2)],
      dtype=[('x', 'S1'), ('y', '<i8')])

  ## Notes

  See `numpy.sort` for notes on the different sorting algorithms.

  Parameters:
  - `axis` (term() default: -1)
  - `kind` (term() default: None)
  - `order` (term() default: None)
  - `stable` (term() keyword-only default: None)

  Returns:
  - `term()`
  """
  @spec sort(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def sort(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :sort, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.tobytes(order='C')

  Construct Python bytes containing the raw data bytes in the array.

  Constructs Python bytes showing a copy of the raw contents of
  data memory. The bytes object is produced in C-order by default.
  This behavior is controlled by the ``order`` parameter.

  ## Parameters

  - `order` - {'C', 'F', 'A'}, optional Controls the memory layout of the bytes object. 'C' means C-order, 'F' means F-order, 'A' (short for *Any*) means 'F' if `a` is Fortran contiguous, 'C' otherwise. Default is 'C'.

  ## Returns

  Returns `s`. bytes Python bytes exhibiting a copy of `a`'s raw data.

  ## Examples

      iex> import numpy as np
      iex> x = np.array([[0, 1], [2, 3]], dtype='<u2')
      iex> x.tobytes()
      b'\x00\x00\x01\x00\x02\x00\x03\x00'
      iex> x.tobytes('C') == x.tobytes()
      True
      iex> x.tobytes('F')
      b'\x00\x00\x02\x00\x01\x00\x03\x00'

  Parameters:
  - `order` (term() default: 'C')

  Returns:
  - `term()`
  """
  @spec tobytes(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def tobytes(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :tobytes, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.min(axis=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

  Return the minimum along a given axis.

  Refer to `numpy.amin` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec min(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def min(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :min, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.conjugate()

  Return the complex conjugate, element-wise.

  Refer to `numpy.conjugate` for full documentation.

  Returns:
  - `term()`
  """
  @spec conjugate(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def conjugate(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :conjugate, [], opts)
  end

  @doc """
  a.nonzero()

  Return the indices of the elements that are non-zero.

  Refer to `numpy.nonzero` for full documentation.

  Returns:
  - `term()`
  """
  @spec nonzero(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def nonzero(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :nonzero, [], opts)
  end

  @doc """
  a.trace(offset=0, axis1=0, axis2=1, dtype=None, out=None)

  Return the sum along diagonals of the array.

  Refer to `numpy.trace` for full documentation.

  Parameters:
  - `offset` (term() default: 0)
  - `axis1` (term() default: 0)
  - `axis2` (term() default: 1)
  - `dtype` (term() default: None)
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec trace(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def trace(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :trace, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.conj()

  Complex-conjugate all elements.

  Refer to `numpy.conjugate` for full documentation.

  Returns:
  - `term()`
  """
  @spec conj(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def conj(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :conj, [], opts)
  end

  @doc """
  a.argmax(axis=None, out=None, *, keepdims=False)

  Return indices of the maximum values along the given axis.

  Refer to `numpy.argmax` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `keepdims` (term() keyword-only default: False)

  Returns:
  - `term()`
  """
  @spec argmax(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def argmax(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :argmax, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.clip(min=<no value>, max=<no value>, out=None, **kwargs)

  Return an array whose values are limited to ``[min, max]``.
  One of max or min must be given.

  Refer to `numpy.clip` for full documentation.

  Parameters:
  - `min` (term() default: None)
  - `max` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec clip(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def clip(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :clip, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.searchsorted(v, side='left', sorter=None)

  Find indices where elements of `v` should be inserted in `a` to maintain order.

  For full documentation, see `numpy.searchsorted`.

  Parameters:
  - `v` (term())
  - `side` (term() default: 'left')
  - `sorter` (term() default: None)

  Returns:
  - `term()`
  """
  @spec searchsorted(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def searchsorted(ref, v, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :searchsorted, [v] ++ List.wrap(args), opts)
  end

  @doc """
  a.round(decimals=0, out=None)

  Return `a` with each element rounded to the given number of decimals.

  Refer to `numpy.around` for full documentation.

  Parameters:
  - `decimals` (term() default: 0)
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec round(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def round(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :round, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.flatten(order='C')

  Return a copy of the array collapsed into one dimension.

  ## Parameters

  - `order` - {'C', 'F', 'A', 'K'}, optional 'C' means to flatten in row-major (C-style) order. 'F' means to flatten in column-major (Fortran- style) order. 'A' means to flatten in column-major order if `a` is Fortran *contiguous* in memory, row-major order otherwise. 'K' means to flatten `a` in the order the elements occur in memory. The default is 'C'.

  ## Returns

  Returns `y`. ndarray A copy of the input array, flattened to one dimension.

  ## Examples

      iex> import numpy as np
      iex> a = np.array([[1,2], [3,4]])
      iex> a.flatten()
      array([1, 2, 3, 4])
      iex> a.flatten('F')
      array([1, 3, 2, 4])

  Parameters:
  - `order` (term() default: 'C')

  Returns:
  - `term()`
  """
  @spec flatten(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def flatten(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :flatten, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.partition(kth, axis=-1, kind='introselect', order=None)

  Partially sorts the elements in the array in such a way that the value of
  the element in k-th position is in the position it would be in a sorted
  array. In the output array, all elements smaller than the k-th element
  are located to the left of this element and all equal or greater are
  located to its right. The ordering of the elements in the two partitions
  on the either side of the k-th element in the output array is undefined.

  ## Parameters

  - `kth` - int or sequence of ints Element index to partition by. The kth element value will be in its final sorted position and all smaller elements will be moved before it and all equal or greater elements behind it. The order of all elements in the partitions is undefined. If provided with a sequence of kth it will partition all elements indexed by kth of them into their sorted position at once.
  - `axis` - int, optional Axis along which to sort. Default is -1, which means sort along the last axis.
  - `kind` - {'introselect'}, optional Selection algorithm. Default is 'introselect'.
  - `order` - str or list of str, optional When `a` is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need to be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

  ## Examples

      iex> import numpy as np
      iex> a = np.array([3, 4, 2, 1])
      iex> a.partition(3)
      iex> a
      array([2, 1, 3, 4]) # may vary

      iex> a.partition((1, 3))
      iex> a
      array([1, 2, 3, 4])

  ## Notes

  See ``np.partition`` for notes on the different algorithms.

  Parameters:
  - `kth` (term())
  - `axis` (term() default: -1)
  - `kind` (term() default: 'introselect')
  - `order` (term() default: None)

  Returns:
  - `term()`
  """
  @spec partition(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def partition(ref, kth, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :partition, [kth] ++ List.wrap(args), opts)
  end

  @doc """
  a.setfield(val, dtype, offset=0)

  Put a value into a specified place in a field defined by a data-type.

  Place `val` into `a`'s field defined by `dtype` and beginning `offset`
  bytes into the field.

  ## Parameters

  - `val` - object Value to be placed in field.
  - `dtype` - dtype object Data-type of the field in which to place `val`.
  - `offset` - int, optional The number of bytes into the field at which to place `val`.

  ## Returns

  Returns `nil`. 

  ## Examples

      iex> import numpy as np
      iex> x = np.eye(3)
      iex> x.getfield(np.float64)
      array([[1.,  0.,  0.],
      [0.,  1.,  0.],
      [0.,  0.,  1.]])
      iex> x.setfield(3, np.int32)
      iex> x.getfield(np.int32)
      array([[3, 3, 3],
      [3, 3, 3],
      [3, 3, 3]], dtype=int32)
      iex> x
      array([[1.0e+000, 1.5e-323, 1.5e-323],
      [1.5e-323, 1.0e+000, 1.5e-323],
      [1.5e-323, 1.5e-323, 1.0e+000]])
      iex> x.setfield(np.eye(3), np.int32)
      iex> x
      array([[1.,  0.,  0.],
      [0.,  1.,  0.],
      [0.,  0.,  1.]])

  Parameters:
  - `val` (term())
  - `dtype` (term())
  - `offset` (term() default: 0)

  Returns:
  - `term()`
  """
  @spec setfield(SnakeBridge.Ref.t(), term(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def setfield(ref, val, dtype, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :setfield, [val, dtype] ++ List.wrap(args), opts)
  end

  @doc """
  a.repeat(repeats, axis=None)

  Repeat elements of an array.

  Refer to `numpy.repeat` for full documentation.

  Parameters:
  - `repeats` (term())
  - `axis` (term() default: None)

  Returns:
  - `term()`
  """
  @spec repeat(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def repeat(ref, repeats, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :repeat, [repeats] ++ List.wrap(args), opts)
  end

  @doc """
  a.mean(axis=None, dtype=None, out=None, *, keepdims=<no value>, where=<no value>)

  Returns the average of the array elements along given axis.

  Refer to `numpy.mean` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec mean(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def mean(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :mean, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.std(axis=None, dtype=None, out=None, ddof=0, *, keepdims=<no value>, where=<no value>, mean=<no value>)

  Returns the standard deviation of the array elements along given axis.

  Refer to `numpy.std` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)
  - `ddof` (term() default: 0)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec std(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def std(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :std, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.take(indices, axis=None, out=None, mode='raise')

  Return an array formed from the elements of `a` at the given indices.

  Refer to `numpy.take` for full documentation.

  Parameters:
  - `indices` (term())
  - `axis` (term() default: None)
  - `out` (term() default: None)
  - `mode` (term() default: 'raise')

  Returns:
  - `term()`
  """
  @spec take(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def take(ref, indices, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :take, [indices] ++ List.wrap(args), opts)
  end

  @doc """
  a.var(axis=None, dtype=None, out=None, ddof=0, *, keepdims=<no value>, where=<no value>, mean=<no value>)

  Returns the variance of the array elements, along given axis.

  Refer to `numpy.var` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)
  - `ddof` (term() default: 0)
  - `kwargs` (term())

  Returns:
  - `term()`
  """
  @spec var(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def var(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :var, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.transpose(*axes)

  Returns a view of the array with axes transposed.

  Refer to `numpy.transpose` for full documentation.

  ## Parameters

  - `axes` - None, tuple of ints, or `n` ints

  ## Returns

  Returns `p`. ndarray View of the array with its axes suitably permuted.

  ## Examples

      iex> import numpy as np
      iex> a = np.array([[1, 2], [3, 4]])
      iex> a
      array([[1, 2],
      [3, 4]])
      iex> a.transpose()
      array([[1, 3],
      [2, 4]])
      iex> a.transpose((1, 0))
      array([[1, 3],
      [2, 4]])
      iex> a.transpose(1, 0)
      array([[1, 3],
      [2, 4]])

      iex> a = np.array([1, 2, 3, 4])
      iex> a
      array([1, 2, 3, 4])
      iex> a.transpose()
      array([1, 2, 3, 4])

  Parameters:
  - `axes` (term())

  Returns:
  - `term()`
  """
  @spec transpose(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def transpose(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :transpose, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.cumsum(axis=None, dtype=None, out=None)

  Return the cumulative sum of the elements along the given axis.

  Refer to `numpy.cumsum` for full documentation.

  Parameters:
  - `axis` (term() default: None)
  - `dtype` (term() default: None)
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec cumsum(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cumsum(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :cumsum, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.swapaxes(axis1, axis2, /)

  Return a view of the array with `axis1` and `axis2` interchanged.

  Refer to `numpy.swapaxes` for full documentation.

  Parameters:
  - `axis1` (term())
  - `axis2` (term())

  Returns:
  - `term()`
  """
  @spec swapaxes(SnakeBridge.Ref.t(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def swapaxes(ref, axis1, axis2, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :swapaxes, [axis1, axis2], opts)
  end

  @doc """
  a.dot(other, /, out=None)

  Refer to :func:`numpy.dot` for full documentation.

  Parameters:
  - `other` (term())
  - `out` (term() default: None)

  Returns:
  - `term()`
  """
  @spec dot(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def dot(ref, other, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :dot, [other] ++ List.wrap(args), opts)
  end

  @doc """
  a.dump(file)

  Dump a pickle of the array to the specified file.
  The array can be read back with pickle.load or numpy.load.

  ## Parameters

  - `file` - str or Path A string naming the dump file.

  Parameters:
  - `file` (term())

  Returns:
  - `term()`
  """
  @spec dump(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def dump(ref, file, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :dump, [file], opts)
  end

  @doc """
  a.argpartition(kth, axis=-1, kind='introselect', order=None)

  Returns the indices that would partition this array.

  Refer to `numpy.argpartition` for full documentation.

  Parameters:
  - `kth` (term())
  - `axis` (term() default: -1)
  - `kind` (term() default: 'introselect')
  - `order` (term() default: None)

  Returns:
  - `term()`
  """
  @spec argpartition(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def argpartition(ref, kth, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :argpartition, [kth] ++ List.wrap(args), opts)
  end

  @doc """
  a.ravel(order='C')

  Return a flattened array.

  Refer to `numpy.ravel` for full documentation.

  Parameters:
  - `order` (term() default: 'C')

  Returns:
  - `term()`
  """
  @spec ravel(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def ravel(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :ravel, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.argsort(axis=-1, kind=None, order=None, *, stable=None)

  Returns the indices that would sort this array.

  Refer to `numpy.argsort` for full documentation.

  Parameters:
  - `axis` (term() default: -1)
  - `kind` (term() default: None)
  - `order` (term() default: None)
  - `stable` (term() keyword-only default: None)

  Returns:
  - `term()`
  """
  @spec argsort(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def argsort(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :argsort, [] ++ List.wrap(args), opts)
  end

  @doc """
  a.dumps()

  Returns the pickle of the array as a string.
  ``pickle.loads`` will convert the string back to an array.

  ## Parameters

  - `None` -

  Returns:
  - `term()`
  """
  @spec dumps(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dumps(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :dumps, [], opts)
  end

  @spec t(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def t(ref) do
    SnakeBridge.Runtime.get_attr(ref, :T)
  end

  @spec base(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def base(ref) do
    SnakeBridge.Runtime.get_attr(ref, :base)
  end

  @spec ctypes(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ctypes(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ctypes)
  end

  @spec data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :data)
  end

  @spec device(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def device(ref) do
    SnakeBridge.Runtime.get_attr(ref, :device)
  end

  @spec dtype(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dtype(ref) do
    SnakeBridge.Runtime.get_attr(ref, :dtype)
  end

  @spec flags(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def flags(ref) do
    SnakeBridge.Runtime.get_attr(ref, :flags)
  end

  @spec flat(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def flat(ref) do
    SnakeBridge.Runtime.get_attr(ref, :flat)
  end

  @spec imag(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def imag(ref) do
    SnakeBridge.Runtime.get_attr(ref, :imag)
  end

  @spec itemsize(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def itemsize(ref) do
    SnakeBridge.Runtime.get_attr(ref, :itemsize)
  end

  @spec m_t(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def m_t(ref) do
    SnakeBridge.Runtime.get_attr(ref, :mT)
  end

  @spec nbytes(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def nbytes(ref) do
    SnakeBridge.Runtime.get_attr(ref, :nbytes)
  end

  @spec ndim(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ndim(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ndim)
  end

  @spec real(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def real(ref) do
    SnakeBridge.Runtime.get_attr(ref, :real)
  end

  @spec shape(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def shape(ref) do
    SnakeBridge.Runtime.get_attr(ref, :shape)
  end

  @spec size(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def size(ref) do
    SnakeBridge.Runtime.get_attr(ref, :size)
  end

  @spec strides(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def strides(ref) do
    SnakeBridge.Runtime.get_attr(ref, :strides)
  end
end
