# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10
# Python module: pylatexenc.latexwalker

defmodule PyLatexEnc.Latexwalker do
  @moduledoc """
  Submodule bindings for `pylatexenc.latexwalker`.
  """

  def __snakebridge_python_name__, do: "pylatexenc.latexwalker"
  def __snakebridge_library__, do: "pylatexenc"
end
