# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10
# Python module: pylatexenc.latexwalker

defmodule PyLatexEnc.Latexwalker do
  @moduledoc """
  The ``latexwalker`` module provides a simple API for parsing LaTeX snippets,

  and representing the contents using a data structure based on node classes.

  LatexWalker will understand the syntax of most common macros.  However,
  ``latexwalker`` is NOT a replacement for a full LaTeX engine.  (Originally,
  ``latexwalker`` was designed to extract useful text for indexing for text
  database searches of LaTeX content.)

  Simple example usage::

      >>> from pylatexenc.latexwalker import LatexWalker, LatexEnvironmentNode
      >>> w = LatexWalker(r\"\"\"
      ... \textbf{Hi there!} Here is \emph{a list}:
      ... \begin{enumerate}[label=(i)]
      ... \item One
      ... \item Two
      ... \end{enumerate}
      ... and $x$ is a variable.
      ... \"\"\")
      >>> (nodelist, pos, len_) = w.get_latex_nodes(pos=0)
      >>> nodelist[0]
      LatexCharsNode(pos=0, len=1, chars='\n')
      >>> nodelist[1]
      LatexMacroNode(pos=1, len=18, macroname='textbf',
      nodeargd=ParsedMacroArgs(argnlist=[LatexGroupNode(pos=8, len=11,
      nodelist=[LatexCharsNode(pos=9, len=9, chars='Hi there!')],
      delimiters=('{', '}'))], argspec='{'), macro_post_space='')
      >>> nodelist[5].isNodeType(LatexEnvironmentNode)
      True
      >>> nodelist[5].environmentname
      'enumerate'
      >>> nodelist[5].nodeargd.argspec
      '['
      >>> nodelist[5].nodeargd.argnlist
      [LatexGroupNode(pos=60, len=11, nodelist=[LatexCharsNode(pos=61, len=9,
      chars='label=(i)')], delimiters=('[', ']'))]
      >>> nodelist[7].latex_verbatim()
      '$x$'

  You can also use `latexwalker` directly in command-line, producing JSON or a
  human-readable node tree::

      $ echo '\textit{italic} text' | latexwalker --output-format=json
      {
        "nodelist": [
          {
            "nodetype": "LatexMacroNode",
            "pos": 0,
            "len": 15,
            "macroname": "textit",
      [...]

      $ latexwalker --help
      [...]

  The parser can be influenced by specifying a collection of known macros and
  environments (the "latex context") that are specified using
  :py:class:`pylatexenc.macrospec.MacroSpec` and
  :py:class:`pylatexenc.macrospec.EnvironmentSpec` objects in a
  :py:class:`pylatexenc.macrospec.LatexContextDb` object.  See the doc of the
  module :py:mod:`pylatexenc.macrospec` for more information.

  ## Version

  - Requested: ~> 2.10
  - Observed at generation: 2.10

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      PyLatexEnc.Latexwalker.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      PyLatexEnc.Latexwalker.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      PyLatexEnc.Latexwalker.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      PyLatexEnc.Latexwalker.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "pylatexenc.latexwalker"
  @doc false
  def __snakebridge_library__, do: "pylatexenc"
end
