# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math stdlib
# Python module: math

defmodule Math do
  @moduledoc """
  This module provides access to the mathematical functions

  defined by the C standard.

  ## Python Docs

  - [Python docs](https://docs.python.org/3/library/math.html)

  ## Version

  - Python stdlib (Python 3.12.3)

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Math.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Math.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Math.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Math.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "math"
  @doc false
  def __snakebridge_library__, do: "math"

  @doc """
  Return the square root of x.

  ## Parameters

  - `x` (term())

  ## Returns

  - `term()`
  """
  @spec sqrt(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sqrt(x, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :sqrt, [x], opts)
  end

  @doc false
  def __functions__ do
    [
      {:sqrt, 1, __MODULE__, "Return the square root of x."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
