# Generated by SnakeBridge v0.7.5 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math stdlib

defmodule Math do
  @moduledoc """
  SnakeBridge bindings for `math`.
  """

  def __snakebridge_python_name__, do: "math"
  def __snakebridge_library__, do: "math"

  @doc """
  Convert a string or number to a floating point number, if possible.

  Returns:
  - `float()`
  """
  @spec pi() :: {:ok, float()} | {:error, Snakepit.Error.t()}
  def pi() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :pi)
  end

  @doc false
  def __functions__ do
    [
      {:pi, 0, __MODULE__, "Convert a string or number to a floating point number, if possible."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
