# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: coverage_report_example stdlib
# Python module: coverage_report_example

defmodule CoverageReportExample do
  @moduledoc """
  Local module for coverage report example.

  ## Python Docs

  - [Python docs](https://docs.python.org/3/library/coverage_report_example.html)

  ## Version

  - Python stdlib (Python 3.12.3)

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      CoverageReportExample.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      CoverageReportExample.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      CoverageReportExample.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      CoverageReportExample.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "coverage_report_example"
  @doc false
  def __snakebridge_library__, do: "coverage_report_example"

  @doc """
  Add two numbers.

  ## Parameters

  - `a` (term())
  - `b` (term())

  ## Returns

  - `term()`
  """
  @spec documented(term(), term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def documented(a, b, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :documented, [a, b], opts)
  end

  @doc """
  Local module for coverage report example.

  ## Parameters

  - `value` (term())

  ## Returns

  - `term()`
  """
  @spec undocumented(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def undocumented(value, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :undocumented, [value], opts)
  end

  @doc false
  def __functions__ do
    [
      {:documented, 2, __MODULE__, "Add two numbers."},
      {:undocumented, 1, __MODULE__, "Local module for coverage report example."}
    ]
  end

  @doc false
  def __classes__ do
    [
      {CoverageReportExample.Example, "Example class for coverage reporting."}
    ]
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
