# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: coverage_report_example stdlib
# Python module: coverage_report_example
# Python class: Example

defmodule CoverageReportExample.Example do
  @moduledoc """
  Example class for coverage reporting.
  """
  def __snakebridge_python_name__, do: "coverage_report_example"
  def __snakebridge_python_class__, do: "Example"
  def __snakebridge_library__, do: "coverage_report_example"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  Parameters:
  - `value` (term())
  """
  @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(value, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [value], opts)
  end

  @doc """
  Increase value by delta.

  Parameters:
  - `delta` (term())

  Returns:
  - `term()`
  """
  @spec increment(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def increment(ref, delta, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :increment, [delta], opts)
  end
end
