# Generated by SnakeBridge v0.7.5 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib

defmodule Json do
  @moduledoc """
  SnakeBridge bindings for `json`.
  """

  def __snakebridge_python_name__, do: "json"
  def __snakebridge_library__, do: "json"

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
