# Generated by SnakeBridge v0.7.3 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: math stdlib

defmodule Math do
  @moduledoc """
  SnakeBridge bindings for `math`.
  """

  def __snakebridge_python_name__, do: "math"
  def __snakebridge_library__, do: "math"

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
