# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json
# Python class: JSONDecoder

defmodule Json.JSONDecoder do
  @moduledoc """
  Simple JSON <https://json.org> decoder

  Performs the following translations in decoding by default:

  ```
  +---------------+-------------------+
  | JSON          | Python            |
  +===============+===================+
  | object        | dict              |
  +---------------+-------------------+
  | array         | list              |
  +---------------+-------------------+
  | string        | str               |
  +---------------+-------------------+
  | number (int)  | int               |
  +---------------+-------------------+
  | number (real) | float             |
  +---------------+-------------------+
  | true          | True              |
  +---------------+-------------------+
  | false         | False             |
  +---------------+-------------------+
  | null          | None              |
  +---------------+-------------------+
  ```

  It also understands ``NaN``, ``Infinity``, and ``-Infinity`` as
  their corresponding ``float`` values, which is outside the JSON spec.
  """
  def __snakebridge_python_name__, do: "json"
  def __snakebridge_python_class__, do: "JSONDecoder"
  def __snakebridge_library__, do: "json"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  ``object_hook``, if specified, will be called with the result

  of every JSON object decoded and its return value will be used in
  place of the given ``dict``.  This can be used to provide custom
  deserializations (e.g. to support JSON-RPC class hinting).

  ``object_pairs_hook``, if specified will be called with the result of
  every JSON object decoded with an ordered list of pairs.  The return
  value of ``object_pairs_hook`` will be used instead of the ``dict``.
  This feature can be used to implement custom decoders.
  If ``object_hook`` is also defined, the ``object_pairs_hook`` takes
  priority.

  ``parse_float``, if specified, will be called with the string
  of every JSON float to be decoded. By default this is equivalent to
  float(num_str). This can be used to use another datatype or parser
  for JSON floats (e.g. decimal.Decimal).

  ``parse_int``, if specified, will be called with the string
  of every JSON int to be decoded. By default this is equivalent to
  int(num_str). This can be used to use another datatype or parser
  for JSON integers (e.g. float).

  ``parse_constant``, if specified, will be called with one of the
  following strings: -Infinity, Infinity, NaN.
  This can be used to raise an exception if invalid JSON numbers
  are encountered.

  If ``strict`` is false (true is the default), then control
  characters will be allowed inside strings.  Control characters in
  this context are those with character codes in the 0-31 range,
  including ``'\t'`` (tab), ``'\n'``, ``'\r'`` and ``'\0'``.

  ## Parameters

  - `object_hook` (term() keyword-only default: None)
  - `parse_float` (term() keyword-only default: None)
  - `parse_int` (term() keyword-only default: None)
  - `parse_constant` (term() keyword-only default: None)
  - `strict` (term() keyword-only default: True)
  - `object_pairs_hook` (term() keyword-only default: None)
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @doc """
  Return the Python representation of ``s`` (a ``str`` instance

  containing a JSON document).

  ## Parameters

  - `s` (term())
  - `w` (term() default: <built-in method match of re.Pattern object at 0x79e7432076b0>)

  ## Returns

  - `term()`
  """
  @spec decode(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def decode(ref, s, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :decode, [s] ++ List.wrap(args), opts)
  end

  @doc """
  Decode a JSON document from ``s`` (a ``str`` beginning with

  a JSON document) and return a 2-tuple of the Python
  representation and the index in ``s`` where the document ended.

  This can be used to decode a JSON document from a string that may
  have extraneous data at the end.

  ## Parameters

  - `s` (term())
  - `idx` (term() default: 0)

  ## Returns

  - `term()`
  """
  @spec raw_decode(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def raw_decode(ref, s, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :raw_decode, [s] ++ List.wrap(args), opts)
  end
end
