# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json
# Python class: JSONEncoder

defmodule Json.JSONEncoder do
  def __snakebridge_python_name__, do: "json"
  def __snakebridge_python_class__, do: "JSONEncoder"
  def __snakebridge_library__, do: "json"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @spec default(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def default(ref, o, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :default, [o], opts)
  end

  @spec encode(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def encode(ref, o, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :encode, [o], opts)
  end

  @spec iterencode(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def iterencode(ref, o, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :iterencode, [o] ++ List.wrap(args), opts)
  end

  @spec item_separator(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def item_separator(ref) do
    SnakeBridge.Runtime.get_attr(ref, :item_separator)
  end

  @spec key_separator(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def key_separator(ref) do
    SnakeBridge.Runtime.get_attr(ref, :key_separator)
  end
end
