# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json
# Python class: JSONEncoder

defmodule Json.JSONEncoder do
  @moduledoc """
  Extensible JSON <https://json.org> encoder for Python data structures.

  Supports the following objects and types by default:

  ```
  +-------------------+---------------+
  | Python            | JSON          |
  +===================+===============+
  | dict              | object        |
  +-------------------+---------------+
  | list, tuple       | array         |
  +-------------------+---------------+
  | str               | string        |
  +-------------------+---------------+
  | int, float        | number        |
  +-------------------+---------------+
  | True              | true          |
  +-------------------+---------------+
  | False             | false         |
  +-------------------+---------------+
  | None              | null          |
  +-------------------+---------------+
  ```

  To extend this to recognize other objects, subclass and implement a
  ``.default()`` method with another method that returns a serializable
  object for ``o`` if possible, otherwise it should call the superclass
  implementation (to raise ``TypeError``).
  """
  def __snakebridge_python_name__, do: "json"
  def __snakebridge_python_class__, do: "JSONEncoder"
  def __snakebridge_library__, do: "json"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructor for JSONEncoder, with sensible defaults.

  If skipkeys is false, then it is a TypeError to attempt
  encoding of keys that are not str, int, float or None.  If
  skipkeys is True, such items are simply skipped.

  If ensure_ascii is true, the output is guaranteed to be str
  objects with all incoming non-ASCII characters escaped.  If
  ensure_ascii is false, the output can contain non-ASCII characters.

  If check_circular is true, then lists, dicts, and custom encoded
  objects will be checked for circular references during encoding to
  prevent an infinite recursion (which would cause an RecursionError).
  Otherwise, no such check takes place.

  If allow_nan is true, then NaN, Infinity, and -Infinity will be
  encoded as such.  This behavior is not JSON specification compliant,
  but is consistent with most JavaScript based encoders and decoders.
  Otherwise, it will be a ValueError to encode such floats.

  If sort_keys is true, then the output of dictionaries will be
  sorted by key; this is useful for regression tests to ensure
  that JSON serializations can be compared on a day-to-day basis.

  If indent is a non-negative integer, then JSON array
  elements and object members will be pretty-printed with that
  indent level.  An indent level of 0 will only insert newlines.
  None is the most compact representation.

  If specified, separators should be an (item_separator, key_separator)
  tuple.  The default is (', ', ': ') if *indent* is ``None`` and
  (',', ': ') otherwise.  To get the most compact JSON representation,
  you should specify (',', ':') to eliminate whitespace.

  If specified, default is a function that gets called for objects
  that can't otherwise be serialized.  It should return a JSON encodable
  version of the object or raise a ``TypeError``.

  ## Parameters

  - `skipkeys` (term() keyword-only default: False)
  - `ensure_ascii` (term() keyword-only default: True)
  - `check_circular` (term() keyword-only default: True)
  - `allow_nan` (term() keyword-only default: True)
  - `sort_keys` (term() keyword-only default: False)
  - `indent` (term() keyword-only default: None)
  - `separators` (term() keyword-only default: None)
  - `default` (term() keyword-only default: None)
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @doc """
  Implement this method in a subclass such that it returns

  a serializable object for ``o``, or calls the base implementation
  (to raise a ``TypeError``).

  For example, to support arbitrary iterators, you could
  implement default like this::

      def default(self, o):
          try:
              iterable = iter(o)
          except TypeError:
              pass
          else:
              return list(iterable)
          # Let the base class default method raise the TypeError
          return super().default(o)

  ## Parameters

  - `o` (term())

  ## Returns

  - `term()`
  """
  @spec default(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def default(ref, o, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :default, [o], opts)
  end

  @doc """
  Return a JSON string representation of a Python data structure.

  ```python
  >>> from json.encoder import JSONEncoder
  >>> JSONEncoder().encode({"foo": ["bar", "baz"]})
  '{"foo": ["bar", "baz"]}'
  ```

  ## Parameters

  - `o` (term())

  ## Returns

  - `term()`
  """
  @spec encode(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def encode(ref, o, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :encode, [o], opts)
  end

  @doc """
  Encode the given object and yield each string

  representation as available.

  For example::

      for chunk in JSONEncoder().iterencode(bigobject):
          mysocket.write(chunk)

  ## Parameters

  - `o` (term())
  - `one_shot` (term() default: False)

  ## Returns

  - `term()`
  """
  @spec iterencode(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def iterencode(ref, o, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :iterencode, [o] ++ List.wrap(args), opts)
  end

  @spec item_separator(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def item_separator(ref) do
    SnakeBridge.Runtime.get_attr(ref, :item_separator)
  end

  @spec key_separator(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def key_separator(ref) do
    SnakeBridge.Runtime.get_attr(ref, :key_separator)
  end
end
