# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: stub_fallback_example stdlib
# Python module: stub_fallback_example

defmodule StubFallbackExample do
  @moduledoc """
  SnakeBridge bindings for `stub_fallback_example`.

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Elixir.StubFallbackExample.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Elixir.StubFallbackExample.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Elixir.StubFallbackExample.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Elixir.StubFallbackExample.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.
  """

  def __snakebridge_python_name__, do: "stub_fallback_example"
  def __snakebridge_library__, do: "stub_fallback_example"

  @doc """
  Add two numbers using the stub signature.

  Parameters:
  - `a` (integer())
  - `b` (integer() default: ...)

  Returns:
  - `integer()`
  """
  @spec stubbed(integer()) :: {:ok, integer()} | {:error, Snakepit.Error.t()}
  @spec stubbed(integer(), keyword()) :: {:ok, integer()} | {:error, Snakepit.Error.t()}
  @spec stubbed(integer(), integer()) :: {:ok, integer()} | {:error, Snakepit.Error.t()}
  @spec stubbed(integer(), integer(), keyword()) ::
          {:ok, integer()} | {:error, Snakepit.Error.t()}
  def stubbed(a) do
    SnakeBridge.Runtime.call(__MODULE__, :stubbed, [a], [])
  end

  def stubbed(a, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :stubbed, [a], opts)
  end

  def stubbed(a, b) do
    SnakeBridge.Runtime.call(__MODULE__, :stubbed, [a, b], [])
  end

  def stubbed(a, b, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :stubbed, [a, b], opts)
  end

  @doc false
  def __functions__ do
    [
      {:stubbed, 1, __MODULE__, "Add two numbers using the stub signature."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
