# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10
# Python module: pylatexenc.latexencode

defmodule PyLatexEnc.Latexencode do
  @moduledoc """
  Submodule bindings for `pylatexenc.latexencode`.
  """

  def __snakebridge_python_name__, do: "pylatexenc.latexencode"
  def __snakebridge_library__, do: "pylatexenc"

  @doc """
  Convert unicode text to LaTeX.

  Parameters:
  - `text` (term())

  Returns:
  - `term()`
  """
  @spec unicode_to_latex(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def unicode_to_latex(text, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :unicode_to_latex, [text], opts)
  end
end
