# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib
# Python module: class_constructor_example
# Python class: Config

defmodule ClassConstructor.Config do
  @moduledoc """
  A class with an optional __init__ argument.
  """
  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_python_class__, do: "Config"
  def __snakebridge_library__, do: "class_constructor_example"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `path` (term())
  - `readonly` (term() default: False)
  """
  @spec new(term()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(path) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path], [])
  end

  def new(path, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path], opts)
  end

  def new(path, readonly) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path, readonly], [])
  end

  def new(path, readonly, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path, readonly], opts)
  end

  @doc """
  Python method `Config.summary`.

  ## Returns

  - `term()`
  """
  @spec summary(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def summary(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :summary, [], opts)
  end
end
