# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib
# Python module: class_constructor_example
# Python class: Config

defmodule ClassConstructor.Config do
  @moduledoc """
  A class with an optional __init__ argument.
  """
  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_python_class__, do: "Config"
  def __snakebridge_library__, do: "class_constructor_example"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `path` (term())
  - `readonly` (term() default: False)
  """
  @spec new(term(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(path, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [path] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `Config.summary`.

  ## Returns

  - `term()`
  """
  @spec summary(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def summary(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :summary, [], opts)
  end
end
