# Generated by SnakeBridge v0.13.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib
# Python module: class_constructor_example
# Python class: EmptyClass

defmodule ClassConstructor.EmptyClass do
  @moduledoc """
  A class with no __init__ arguments.
  """
  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_python_class__, do: "EmptyClass"
  def __snakebridge_library__, do: "class_constructor_example"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end
end
