# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: class_constructor_example stdlib
# Python module: class_constructor_example
# Python class: Point

defmodule ClassConstructor.Point do
  def __snakebridge_python_name__, do: "class_constructor_example"
  def __snakebridge_python_class__, do: "Point"
  def __snakebridge_library__, do: "class_constructor_example"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(x, y, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [x, y], opts)
  end

  @spec magnitude(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def magnitude(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :magnitude, [], opts)
  end
end
