# Generated by SnakeBridge v0.7.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: streaming_example stdlib

defmodule Streaming do
  @moduledoc """
  SnakeBridge bindings for `streaming_example`.
  """

  def __snakebridge_python_name__, do: "streaming_example"
  def __snakebridge_library__, do: "streaming_example"

  @doc """
  Generate either a full response or a stream of chunks.
  """
  @spec generate(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def generate(prompt, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :generate, [prompt], opts)
  end

  @doc """
  Streaming variant of `generate/2`.

  The callback receives chunks as they arrive.
  """
  @spec generate_stream(term(), keyword(), (term() -> any())) ::
          :ok | {:error, Snakepit.Error.t()}
  def generate_stream(prompt, opts \\ [], callback) when is_function(callback, 1) do
    SnakeBridge.Runtime.stream(__MODULE__, :generate, [prompt], opts, callback)
  end

  @doc false
  def __functions__ do
    [
      {:generate, 1, __MODULE__, "Generate either a full response or a stream of chunks."}
    ]
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
