# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.encoder

defmodule Json.Encoder do
  @moduledoc """
  Implementation of JSONEncoder

  ## Python Docs

  - [Python docs](https://docs.python.org/3/library/json.html)

  ## Version

  - Python stdlib (Python 3.12.3)

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Json.Encoder.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Json.Encoder.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Json.Encoder.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Json.Encoder.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "json.encoder"
  @doc false
  def __snakebridge_library__, do: "json"

  @doc """
  Return a JSON representation of a Python string

  ## Parameters

  - `s` (term())

  ## Returns

  - `term()`
  """
  @spec py_encode_basestring(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def py_encode_basestring(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :py_encode_basestring, [s], opts)
  end

  @doc """
  Return an ASCII-only JSON representation of a Python string

  ## Parameters

  - `s` (term())

  ## Returns

  - `term()`
  """
  @spec py_encode_basestring_ascii(term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def py_encode_basestring_ascii(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :py_encode_basestring_ascii, [s], opts)
  end
end
