# Generated by SnakeBridge v0.12.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.encoder

defmodule Json.Encoder do
  @moduledoc """
  Submodule bindings for `json.encoder`.
  """

  def __snakebridge_python_name__, do: "json.encoder"
  def __snakebridge_library__, do: "json"

  @doc """
  Return a JSON representation of a Python string

  Parameters:
  - `s` (term())

  Returns:
  - `term()`
  """
  @spec py_encode_basestring(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def py_encode_basestring(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :py_encode_basestring, [s], opts)
  end

  @doc """
  Return an ASCII-only JSON representation of a Python string

  Parameters:
  - `s` (term())

  Returns:
  - `term()`
  """
  @spec py_encode_basestring_ascii(term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def py_encode_basestring_ascii(s, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :py_encode_basestring_ascii, [s], opts)
  end
end
