# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.decoder

defmodule Json.Decoder do
  @moduledoc """
  Submodule bindings for `json.decoder`.
  """

  def __snakebridge_python_name__, do: "json.decoder"
  def __snakebridge_library__, do: "json"
end
