# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.decoder
# Python class: JSONDecodeError

defmodule Json.Decoder.JSONDecodeError do
  @moduledoc """
  Subclass of ValueError with the following additional properties:

  msg: The unformatted error message
  doc: The JSON document being parsed
  pos: The start index of doc where parsing failed
  lineno: The line corresponding to pos
  colno: The column corresponding to pos
  """
  def __snakebridge_python_name__, do: "json.decoder"
  def __snakebridge_python_class__, do: "JSONDecodeError"
  def __snakebridge_library__, do: "json"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `msg` (term())
  - `doc` (term())
  - `pos` (term())
  """
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(msg, doc, pos, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [msg, doc, pos], opts)
  end

  @doc """
  Add a note to the exception

  ## Parameters

  - `note` (term())

  ## Returns

  - `term()`
  """
  @spec add_note(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def add_note(ref, note, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add_note, [note], opts)
  end

  @doc """
  Set self.__traceback__ to tb and return self.

  ## Parameters

  - `tb` (term())

  ## Returns

  - `term()`
  """
  @spec with_traceback(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def with_traceback(ref, tb, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :with_traceback, [tb], opts)
  end

  @spec args(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def args(ref) do
    SnakeBridge.Runtime.get_attr(ref, :args)
  end
end
