# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.scanner

defmodule Json.Scanner do
  @moduledoc """
  Submodule bindings for `json.scanner`.
  """

  def __snakebridge_python_name__, do: "json.scanner"
  def __snakebridge_library__, do: "json"
end
