# Generated by SnakeBridge v0.13.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: json stdlib
# Python module: json.scanner
# Python class: make_scanner

defmodule Json.Scanner.MakeScanner do
  @moduledoc """
  JSON scanner object
  """
  def __snakebridge_python_name__, do: "json.scanner"
  def __snakebridge_python_class__, do: "make_scanner"
  def __snakebridge_library__, do: "json"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @spec object_hook(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def object_hook(ref) do
    SnakeBridge.Runtime.get_attr(ref, :object_hook)
  end

  @spec object_pairs_hook(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def object_pairs_hook(ref) do
    SnakeBridge.Runtime.get_attr(ref, :object_pairs_hook)
  end

  @spec parse_constant(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse_constant(ref) do
    SnakeBridge.Runtime.get_attr(ref, :parse_constant)
  end

  @spec parse_float(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse_float(ref) do
    SnakeBridge.Runtime.get_attr(ref, :parse_float)
  end

  @spec parse_int(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse_int(ref) do
    SnakeBridge.Runtime.get_attr(ref, :parse_int)
  end

  @spec strict(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def strict(ref) do
    SnakeBridge.Runtime.get_attr(ref, :strict)
  end
end
